// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: cosd_oc.proto

package junos_telemetry_interface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Qos struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Interfaces       *QosInterfacesType       `protobuf:"bytes,151,opt,name=interfaces" json:"interfaces,omitempty"`
	ForwardingGroups *QosForwardingGroupsType `protobuf:"bytes,152,opt,name=forwarding_groups,json=forwardingGroups" json:"forwarding_groups,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Qos) Reset() {
	*x = Qos{}
	mi := &file_cosd_oc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Qos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Qos) ProtoMessage() {}

func (x *Qos) ProtoReflect() protoreflect.Message {
	mi := &file_cosd_oc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Qos.ProtoReflect.Descriptor instead.
func (*Qos) Descriptor() ([]byte, []int) {
	return file_cosd_oc_proto_rawDescGZIP(), []int{0}
}

func (x *Qos) GetInterfaces() *QosInterfacesType {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *Qos) GetForwardingGroups() *QosForwardingGroupsType {
	if x != nil {
		return x.ForwardingGroups
	}
	return nil
}

type QosInterfacesType struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Interface     []*QosInterfacesTypeInterfaceList `protobuf:"bytes,151,rep,name=interface" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QosInterfacesType) Reset() {
	*x = QosInterfacesType{}
	mi := &file_cosd_oc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QosInterfacesType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosInterfacesType) ProtoMessage() {}

func (x *QosInterfacesType) ProtoReflect() protoreflect.Message {
	mi := &file_cosd_oc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosInterfacesType.ProtoReflect.Descriptor instead.
func (*QosInterfacesType) Descriptor() ([]byte, []int) {
	return file_cosd_oc_proto_rawDescGZIP(), []int{0, 0}
}

func (x *QosInterfacesType) GetInterface() []*QosInterfacesTypeInterfaceList {
	if x != nil {
		return x.Interface
	}
	return nil
}

type QosForwardingGroupsType struct {
	state           protoimpl.MessageState                        `protogen:"open.v1"`
	ForwardingGroup []*QosForwardingGroupsTypeForwardingGroupList `protobuf:"bytes,151,rep,name=forwarding_group,json=forwardingGroup" json:"forwarding_group,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QosForwardingGroupsType) Reset() {
	*x = QosForwardingGroupsType{}
	mi := &file_cosd_oc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QosForwardingGroupsType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosForwardingGroupsType) ProtoMessage() {}

func (x *QosForwardingGroupsType) ProtoReflect() protoreflect.Message {
	mi := &file_cosd_oc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosForwardingGroupsType.ProtoReflect.Descriptor instead.
func (*QosForwardingGroupsType) Descriptor() ([]byte, []int) {
	return file_cosd_oc_proto_rawDescGZIP(), []int{0, 1}
}

func (x *QosForwardingGroupsType) GetForwardingGroup() []*QosForwardingGroupsTypeForwardingGroupList {
	if x != nil {
		return x.ForwardingGroup
	}
	return nil
}

type QosInterfacesTypeInterfaceList struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	InterfaceId   *string                                         `protobuf:"bytes,51,opt,name=interface_id,json=interfaceId" json:"interface_id,omitempty"`
	State         *QosInterfacesTypeInterfaceListStateType        `protobuf:"bytes,151,opt,name=state" json:"state,omitempty"`
	InterfaceRef  *QosInterfacesTypeInterfaceListInterfaceRefType `protobuf:"bytes,152,opt,name=interface_ref,json=interfaceRef" json:"interface_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QosInterfacesTypeInterfaceList) Reset() {
	*x = QosInterfacesTypeInterfaceList{}
	mi := &file_cosd_oc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QosInterfacesTypeInterfaceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosInterfacesTypeInterfaceList) ProtoMessage() {}

func (x *QosInterfacesTypeInterfaceList) ProtoReflect() protoreflect.Message {
	mi := &file_cosd_oc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosInterfacesTypeInterfaceList.ProtoReflect.Descriptor instead.
func (*QosInterfacesTypeInterfaceList) Descriptor() ([]byte, []int) {
	return file_cosd_oc_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *QosInterfacesTypeInterfaceList) GetInterfaceId() string {
	if x != nil && x.InterfaceId != nil {
		return *x.InterfaceId
	}
	return ""
}

func (x *QosInterfacesTypeInterfaceList) GetState() *QosInterfacesTypeInterfaceListStateType {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *QosInterfacesTypeInterfaceList) GetInterfaceRef() *QosInterfacesTypeInterfaceListInterfaceRefType {
	if x != nil {
		return x.InterfaceRef
	}
	return nil
}

type QosInterfacesTypeInterfaceListStateType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceId   *string                `protobuf:"bytes,51,opt,name=interface_id,json=interfaceId" json:"interface_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QosInterfacesTypeInterfaceListStateType) Reset() {
	*x = QosInterfacesTypeInterfaceListStateType{}
	mi := &file_cosd_oc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QosInterfacesTypeInterfaceListStateType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosInterfacesTypeInterfaceListStateType) ProtoMessage() {}

func (x *QosInterfacesTypeInterfaceListStateType) ProtoReflect() protoreflect.Message {
	mi := &file_cosd_oc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosInterfacesTypeInterfaceListStateType.ProtoReflect.Descriptor instead.
func (*QosInterfacesTypeInterfaceListStateType) Descriptor() ([]byte, []int) {
	return file_cosd_oc_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *QosInterfacesTypeInterfaceListStateType) GetInterfaceId() string {
	if x != nil && x.InterfaceId != nil {
		return *x.InterfaceId
	}
	return ""
}

type QosInterfacesTypeInterfaceListInterfaceRefType struct {
	state         protoimpl.MessageState                                   `protogen:"open.v1"`
	State         *QosInterfacesTypeInterfaceListInterfaceRefTypeStateType `protobuf:"bytes,151,opt,name=state" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QosInterfacesTypeInterfaceListInterfaceRefType) Reset() {
	*x = QosInterfacesTypeInterfaceListInterfaceRefType{}
	mi := &file_cosd_oc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QosInterfacesTypeInterfaceListInterfaceRefType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosInterfacesTypeInterfaceListInterfaceRefType) ProtoMessage() {}

func (x *QosInterfacesTypeInterfaceListInterfaceRefType) ProtoReflect() protoreflect.Message {
	mi := &file_cosd_oc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosInterfacesTypeInterfaceListInterfaceRefType.ProtoReflect.Descriptor instead.
func (*QosInterfacesTypeInterfaceListInterfaceRefType) Descriptor() ([]byte, []int) {
	return file_cosd_oc_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

func (x *QosInterfacesTypeInterfaceListInterfaceRefType) GetState() *QosInterfacesTypeInterfaceListInterfaceRefTypeStateType {
	if x != nil {
		return x.State
	}
	return nil
}

type QosInterfacesTypeInterfaceListInterfaceRefTypeStateType struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Interface          *string                `protobuf:"bytes,51,opt,name=interface" json:"interface,omitempty"`
	JnxIflsetinterface *string                `protobuf:"bytes,52,opt,name=jnx_iflsetinterface,json=jnxIflsetinterface" json:"jnx_iflsetinterface,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QosInterfacesTypeInterfaceListInterfaceRefTypeStateType) Reset() {
	*x = QosInterfacesTypeInterfaceListInterfaceRefTypeStateType{}
	mi := &file_cosd_oc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QosInterfacesTypeInterfaceListInterfaceRefTypeStateType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosInterfacesTypeInterfaceListInterfaceRefTypeStateType) ProtoMessage() {}

func (x *QosInterfacesTypeInterfaceListInterfaceRefTypeStateType) ProtoReflect() protoreflect.Message {
	mi := &file_cosd_oc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosInterfacesTypeInterfaceListInterfaceRefTypeStateType.ProtoReflect.Descriptor instead.
func (*QosInterfacesTypeInterfaceListInterfaceRefTypeStateType) Descriptor() ([]byte, []int) {
	return file_cosd_oc_proto_rawDescGZIP(), []int{0, 0, 0, 1, 0}
}

func (x *QosInterfacesTypeInterfaceListInterfaceRefTypeStateType) GetInterface() string {
	if x != nil && x.Interface != nil {
		return *x.Interface
	}
	return ""
}

func (x *QosInterfacesTypeInterfaceListInterfaceRefTypeStateType) GetJnxIflsetinterface() string {
	if x != nil && x.JnxIflsetinterface != nil {
		return *x.JnxIflsetinterface
	}
	return ""
}

type QosForwardingGroupsTypeForwardingGroupList struct {
	state         protoimpl.MessageState                               `protogen:"open.v1"`
	Name          *string                                              `protobuf:"bytes,51,opt,name=name" json:"name,omitempty"`
	State         *QosForwardingGroupsTypeForwardingGroupListStateType `protobuf:"bytes,151,opt,name=state" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QosForwardingGroupsTypeForwardingGroupList) Reset() {
	*x = QosForwardingGroupsTypeForwardingGroupList{}
	mi := &file_cosd_oc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QosForwardingGroupsTypeForwardingGroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosForwardingGroupsTypeForwardingGroupList) ProtoMessage() {}

func (x *QosForwardingGroupsTypeForwardingGroupList) ProtoReflect() protoreflect.Message {
	mi := &file_cosd_oc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosForwardingGroupsTypeForwardingGroupList.ProtoReflect.Descriptor instead.
func (*QosForwardingGroupsTypeForwardingGroupList) Descriptor() ([]byte, []int) {
	return file_cosd_oc_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *QosForwardingGroupsTypeForwardingGroupList) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *QosForwardingGroupsTypeForwardingGroupList) GetState() *QosForwardingGroupsTypeForwardingGroupListStateType {
	if x != nil {
		return x.State
	}
	return nil
}

type QosForwardingGroupsTypeForwardingGroupListStateType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,51,opt,name=name" json:"name,omitempty"`
	OutputQueue   *string                `protobuf:"bytes,52,opt,name=output_queue,json=outputQueue" json:"output_queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QosForwardingGroupsTypeForwardingGroupListStateType) Reset() {
	*x = QosForwardingGroupsTypeForwardingGroupListStateType{}
	mi := &file_cosd_oc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QosForwardingGroupsTypeForwardingGroupListStateType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosForwardingGroupsTypeForwardingGroupListStateType) ProtoMessage() {}

func (x *QosForwardingGroupsTypeForwardingGroupListStateType) ProtoReflect() protoreflect.Message {
	mi := &file_cosd_oc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosForwardingGroupsTypeForwardingGroupListStateType.ProtoReflect.Descriptor instead.
func (*QosForwardingGroupsTypeForwardingGroupListStateType) Descriptor() ([]byte, []int) {
	return file_cosd_oc_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

func (x *QosForwardingGroupsTypeForwardingGroupListStateType) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *QosForwardingGroupsTypeForwardingGroupListStateType) GetOutputQueue() string {
	if x != nil && x.OutputQueue != nil {
		return *x.OutputQueue
	}
	return ""
}

var file_cosd_oc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*JuniperNetworksSensors)(nil),
		ExtensionType: (*Qos)(nil),
		Field:         134,
		Name:          "jnpr_qos_ext",
		Tag:           "bytes,134,opt,name=jnpr_qos_ext",
		Filename:      "cosd_oc.proto",
	},
}

// Extension fields to JuniperNetworksSensors.
var (
	// optional qos jnpr_qos_ext = 134;
	E_JnprQosExt = &file_cosd_oc_proto_extTypes[0]
)

var File_cosd_oc_proto protoreflect.FileDescriptor

var file_cosd_oc_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x73, 0x64, 0x5f, 0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x13, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x74, 0x6f, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x08, 0x0a, 0x03, 0x71, 0x6f, 0x73, 0x12, 0x35, 0x0a, 0x0a,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x97, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x71, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x11, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x98, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x71, 0x6f, 0x73, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x10, 0x66, 0x6f,
	0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x1a, 0xb6,
	0x04, 0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18,
	0x97, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x71, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x09, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x1a, 0xde, 0x03, 0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0c, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x33, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x05, 0x82, 0x40, 0x02, 0x08, 0x01, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x45, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x97, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x71, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x5c, 0x0a, 0x0d, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x98, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x36, 0x2e, 0x71, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x5f, 0x72, 0x65, 0x66, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x66, 0x1a, 0x2f, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x33, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x64, 0x1a, 0xcb, 0x01, 0x0a, 0x12, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x58, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x97, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x41, 0x2e, 0x71, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f,
	0x72, 0x65, 0x66, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x5b, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x33, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x6a, 0x6e, 0x78, 0x5f, 0x69, 0x66,
	0x6c, 0x73, 0x65, 0x74, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x34, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x6a, 0x6e, 0x78, 0x49, 0x66, 0x6c, 0x73, 0x65, 0x74, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x1a, 0xc6, 0x02, 0x0a, 0x16, 0x66, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x5d, 0x0a, 0x10, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x97, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e,
	0x71, 0x6f, 0x73, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x52, 0x0f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x1a, 0xcc, 0x01, 0x0a, 0x15, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x33, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0x82, 0x40, 0x02, 0x08, 0x01,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x53, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x97, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x71, 0x6f, 0x73, 0x2e, 0x66, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x43, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x33, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x34, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x3a, 0x40, 0x0a, 0x0c, 0x6a, 0x6e, 0x70, 0x72, 0x5f, 0x71, 0x6f, 0x73, 0x5f, 0x65, 0x78, 0x74,
	0x12, 0x17, 0x2e, 0x4a, 0x75, 0x6e, 0x69, 0x70, 0x65, 0x72, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x18, 0x86, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x04, 0x2e, 0x71, 0x6f, 0x73, 0x52, 0x0a, 0x6a, 0x6e, 0x70, 0x72, 0x51, 0x6f, 0x73, 0x45,
	0x78, 0x74, 0x42, 0x1d, 0x5a, 0x1b, 0x2e, 0x2f, 0x6a, 0x75, 0x6e, 0x6f, 0x73, 0x5f, 0x74, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65,
})

var (
	file_cosd_oc_proto_rawDescOnce sync.Once
	file_cosd_oc_proto_rawDescData []byte
)

func file_cosd_oc_proto_rawDescGZIP() []byte {
	file_cosd_oc_proto_rawDescOnce.Do(func() {
		file_cosd_oc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cosd_oc_proto_rawDesc), len(file_cosd_oc_proto_rawDesc)))
	})
	return file_cosd_oc_proto_rawDescData
}

var file_cosd_oc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cosd_oc_proto_goTypes = []any{
	(*Qos)(nil),                                                     // 0: qos
	(*QosInterfacesType)(nil),                                       // 1: qos.interfaces_type
	(*QosForwardingGroupsType)(nil),                                 // 2: qos.forwarding_groups_type
	(*QosInterfacesTypeInterfaceList)(nil),                          // 3: qos.interfaces_type.interface_list
	(*QosInterfacesTypeInterfaceListStateType)(nil),                 // 4: qos.interfaces_type.interface_list.state_type
	(*QosInterfacesTypeInterfaceListInterfaceRefType)(nil),          // 5: qos.interfaces_type.interface_list.interface_ref_type
	(*QosInterfacesTypeInterfaceListInterfaceRefTypeStateType)(nil), // 6: qos.interfaces_type.interface_list.interface_ref_type.state_type
	(*QosForwardingGroupsTypeForwardingGroupList)(nil),              // 7: qos.forwarding_groups_type.forwarding_group_list
	(*QosForwardingGroupsTypeForwardingGroupListStateType)(nil),     // 8: qos.forwarding_groups_type.forwarding_group_list.state_type
	(*JuniperNetworksSensors)(nil),                                  // 9: JuniperNetworksSensors
}
var file_cosd_oc_proto_depIdxs = []int32{
	1,  // 0: qos.interfaces:type_name -> qos.interfaces_type
	2,  // 1: qos.forwarding_groups:type_name -> qos.forwarding_groups_type
	3,  // 2: qos.interfaces_type.interface:type_name -> qos.interfaces_type.interface_list
	7,  // 3: qos.forwarding_groups_type.forwarding_group:type_name -> qos.forwarding_groups_type.forwarding_group_list
	4,  // 4: qos.interfaces_type.interface_list.state:type_name -> qos.interfaces_type.interface_list.state_type
	5,  // 5: qos.interfaces_type.interface_list.interface_ref:type_name -> qos.interfaces_type.interface_list.interface_ref_type
	6,  // 6: qos.interfaces_type.interface_list.interface_ref_type.state:type_name -> qos.interfaces_type.interface_list.interface_ref_type.state_type
	8,  // 7: qos.forwarding_groups_type.forwarding_group_list.state:type_name -> qos.forwarding_groups_type.forwarding_group_list.state_type
	9,  // 8: jnpr_qos_ext:extendee -> JuniperNetworksSensors
	0,  // 9: jnpr_qos_ext:type_name -> qos
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	9,  // [9:10] is the sub-list for extension type_name
	8,  // [8:9] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cosd_oc_proto_init() }
func file_cosd_oc_proto_init() {
	if File_cosd_oc_proto != nil {
		return
	}
	file_telemetry_top_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cosd_oc_proto_rawDesc), len(file_cosd_oc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_cosd_oc_proto_goTypes,
		DependencyIndexes: file_cosd_oc_proto_depIdxs,
		MessageInfos:      file_cosd_oc_proto_msgTypes,
		ExtensionInfos:    file_cosd_oc_proto_extTypes,
	}.Build()
	File_cosd_oc_proto = out.File
	file_cosd_oc_proto_goTypes = nil
	file_cosd_oc_proto_depIdxs = nil
}
